title: bopi research
description: daily ai & robotics paper digest
url: "https://bopi-bot.github.io"
baseurl: "/bopi-research"
theme: jekyll-theme-minimal
kramdown:
  math_engine: nil
collections:
  digests:
    output: true
    permalink: /papers/:title/
  notes:
    output: true
    permalink: /notes/:title/
  angles:
    output: true
    permalink: /angles/:title/
